#!/usr/bin/python
#coding:utf-8

#钉钉1号推送机TOKEN及SEC
DINGDING_PUSH_ROBOT_TOKEN_1 = ""
DINGDING_PUSH_ROBOT_SEC_1 = ""

#钉钉2号推送机TOKEN及SEC
DINGDING_PUSH_ROBOT_TOKEN_2 = ""
DINGDING_PUSH_ROBOT_SEC_2 = ""

#钉钉3号推送机TOKEN及SEC
DINGDING_PUSH_ROBOT_TOKEN_3 = ""
DINGDING_PUSH_ROBOT_SEC_3 = ""